{% set name = "acwater" %}
{% set version = "0.4.1" %}
{% set python_min = "3.11" %}  # polymer is not 3.10-compatible

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.awi.de/phytooptics/acwater/-/archive/v{{ version }}/acwater-v{{ version }}.tar.gz
  sha256: 29f2496de4c368a77bc9c27086b383c746a469194ce113a95328a5c5652193bf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - acwater = acwater.cli:main

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}

  run:
    - python >={{ python_min }}
    - enpt
    - polymer
    - netcdf4
    - numpy
    - pandas
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - acwater
    - enpt
    - polymer

about:
  home: https://gitlab.awi.de/phytooptics/acwater
  summary: Atmospheric correction of EnMAP hyperspectral data for water surfaces (ACwater), based on EnPT and Polymer.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - josbel96
    - danschef
